# Generated by Django 3.2.15 on 2022-11-24 09:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=500)),
                ('description', tinymce.models.HTMLField()),
                ('requirements', tinymce.models.HTMLField()),
                ('slug', models.SlugField(blank=True, max_length=500, verbose_name='Slug')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('application_email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Careers',
                'verbose_name_plural': 'Careers',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ipAddress', models.CharField(blank=True, max_length=255)),
                ('consented', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consent',
                'verbose_name_plural': 'Consents',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Porttfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('logo', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-modified'],
                'managed': True,
            },
        ),
    ]
