# Generated by Django 3.2.15 on 2022-11-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_career_consent_porttfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='slug',
        ),
        migrations.AddField(
            model_name='career',
            name='logo',
            field=models.URLField(default='https://panteracapital.com/wp-content/uploads/2022/10/Logo-2.png'),
        ),
    ]
